import test from 'node:test';
import assert from 'node:assert/strict';
import {audit,validateInput,localDraft,validateDraft} from '../lib/listing.mjs';
import {createServer} from '../server.mjs';
const listing={title:'Blue pottery mug',description:'A blue pottery mug made in my home studio. The rounded handle is comfortable to hold while enjoying a morning coffee.',keyword:'pottery mug',voice:'Warm',tags:'pottery mug, pottery mug, this tag is far too long for a tag',details:'Stoneware, 12 ounces.'};
test('audit flags duplicates and oversized tags without presenting ranking data',()=>{const result=audit(listing);assert.equal(result.checks.find(c=>c.name==='No repeated tags').pass,false);assert.equal(result.checks.find(c=>c.name==='Tag length').pass,false);assert.equal(result.checks.find(c=>c.name==='Search phrase in title').pass,true);assert.match(result.note,/not an Etsy ranking/);});
test('input rejects empty, malformed and oversized data',()=>{for(const value of [null,[],{}, {title:5},{title:'x',description:'x'.repeat(12001)}])assert.throws(()=>validateInput(value));});
test('local draft preserves facts, removes duplicate or oversized tags',()=>{const result=localDraft(listing);assert.equal(result.description,listing.description+'\n\n'+listing.details);assert.deepEqual(result.tags,['pottery mug']);assert.equal(result.mode,'local');});
test('model output is validated independently of schema',()=>{assert.throws(()=>validateDraft({title:'x',description:'x',tags:['Mug','mug'],notes:[]}));assert.throws(()=>validateDraft({title:'x'.repeat(141),description:'x',tags:[],notes:[]}));});
async function serve(t,options={}){const server=createServer(options);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();}));return `http://127.0.0.1:${server.address().port}`;}
const post=(base,path,body,headers={})=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('local flow, asset allowlist and request boundaries',async t=>{const base=await serve(t,{apiKey:''});assert.equal((await fetch(base)).status,200);assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);assert.deepEqual(await (await fetch(base+'/api/config')).json(),{aiEnabled:false});assert.equal((await post(base,'/api/audit',listing)).status,200);assert.equal((await (await post(base,'/api/draft',listing)).json()).mode,'local');assert.equal((await post(base,'/api/draft',{...listing,mode:'ai',consent:true})).status,503);assert.equal((await post(base,'/api/audit',{})).status,400);assert.equal((await post(base,'/api/audit',listing,{Origin:'https://untrusted.example'})).status,403);assert.equal((await post(base,'/api/audit',{title:'x'.repeat(51000)})).status,413);});
test('AI requires consent and uses structured output with non-stored responses',async t=>{let calls=0;const base=await serve(t,{apiKey:'test-key',fetcher:async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.equal(JSON.parse(body.input).title,listing.title);return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({title:'Blue pottery mug',tags:['pottery mug'],description:listing.description,notes:['Review details.']})}]}]}));}});assert.equal((await post(base,'/api/draft',{...listing,mode:'ai'})).status,400);assert.equal(calls,0);const result=await post(base,'/api/draft',{...listing,mode:'ai',consent:true});assert.equal(result.status,200);assert.equal((await result.json()).mode,'ai');assert.equal(calls,1);});
test('provider failures do not leak secrets or silently return a local draft',async t=>{const base=await serve(t,{apiKey:'secret',fetcher:async()=>new Response('secret provider details',{status:401})});const response=await post(base,'/api/draft',{...listing,mode:'ai',consent:true});assert.equal(response.status,502);assert.doesNotMatch(await response.text(),/secret/);});
test('refused or invalid model content fails safely',async t=>{const base=await serve(t,{apiKey:'test',fetcher:async()=>new Response(JSON.stringify({status:'completed',output:[{content:[{type:'refusal',refusal:'No'}]}]}))});assert.equal((await post(base,'/api/draft',{...listing,mode:'ai',consent:true})).status,502);});
